// File generated by FlutterFire CLI.
// This is a placeholder - replace with your actual Firebase configuration
// Run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAya5qwTO63QH5y5ml7jFVFlAetFLWCS4M',
    appId: '1:165291680266:android:d0a5bd5cecd21588c9b5f3',
    messagingSenderId: '165291680266',
    projectId: 'native-acfca',
    storageBucket: 'native-acfca.firebasestorage.app',
  );
}
